from Animal import *
from Aviary import *
Petya = Elefant('Петя', '5 кг сена', '20 лет')
Simba = Tiger('Симба', '5 кг мяса или рыбы', '5 лет')
Matilda = Pinguin('Матильда', '0.3 рыбы',  '1 год')
Zlata = Dog('Злата', '1 кг корма', '2 года')
Suzi = Sheep('Сьюзи', '2 кг сена', '5 лет')
Vladislav = Wolf('Владислав', '5 кг мяса', '12 лет')
Manny = Giraffe('Мэнни', '3 кг сена', '20 лет')
Miron = Lion('Мирон', '10 кг мяса', '7 лет')
Danya = Goat('Даня', '7 кг сена', '16 лет')

Petya.eat()
Petya.sound_animal()
Petya.play()
Simba.eat()
Simba.sound_animal()
Simba.play()
Matilda.eat()
Matilda.sound_animal()
Matilda.play()
Zlata.eat()
Zlata.sound_animal()
Zlata.play()
Suzi.eat()
Suzi.sound_animal()
Suzi.play()
Vladislav.eat()
Vladislav.sound_animal()
Vladislav.play()
Manny.eat()
Manny.sound_animal()
Manny.play()
Miron.eat()
Miron.sound_animal()
Miron.play()
Danya.eat()
Danya.sound_animal()
Danya.play()

V = Aviary('Elefant', "5 кг сена", "Пустыня")
V.add(Pinguin('Матильда', '0.3 рыбы',  '1 год'))
